import { useState } from 'react'
import { Firebase, routes } from '@health-box/common'
import { Box, Button, styled, TextField, Typography } from '@mui/material'
import Head from 'next/head'
import Link from 'next/link'

const Wrapper = styled(Box)(() => ({
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  height: '100vh',
  flexDirection: 'column',
  background:
    'radial-gradient(circle, rgba(76,215,246,1) 0%, rgba(225,124,253,1) 100%)',
}))

const Body = styled(Box)(({ theme }) => ({
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  flexDirection: 'column',
  background: theme.palette.background.default,
  padding: '60px',
  borderRadius: '16px',
}))

const Title = styled(Typography)(({ theme }) => ({
  fontWeight: 'bold',
  color: theme.palette.primary.main,
  marginBottom: '50px',
}))

const Form = styled(Box)(() => ({
  display: 'flex',
  flexDirection: 'column',
  alignItems: 'center',
  width: '600px',
  gap: '24px',
  fontSize: '24px',
}))

const Input = styled(TextField)(() => ({
  width: '100%',
}))

const FormButton = styled(Button)(() => ({
  fontSize: '24px',
  fontWeight: 'bold',
  padding: '18px',
  width: '400px',
  marginTop: '40px',
}))

export default function Register() {
  const [firstName, setFirstName] = useState('')
  const [lastName, setLastName] = useState('')
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')

  const signUp = () => {
    Firebase.signUp(firstName, lastName, email, password)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper component="main">
        <Body>
          <Title variant="h2">Регестрация</Title>

          <Form component="form">
            <Input
              label="Имя"
              variant="outlined"
              value={firstName}
              onChange={(e) => setFirstName(e.target.value)}
            />
            <Input
              label="Фамилия"
              variant="outlined"
              value={lastName}
              onChange={(e) => setLastName(e.target.value)}
            />
            <Input
              label="E-mail"
              variant="outlined"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
            />
            <Input
              label="Пароль"
              variant="outlined"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
            />
            <FormButton size="large" variant="contained" onClick={signUp}>
              Вперед
            </FormButton>

            <Typography>
              Если у вас уже есть аккаунт -{' '}
              <Link href={routes.login}>войдите</Link>
            </Typography>
          </Form>
        </Body>
      </Wrapper>
    </>
  )
}
